// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHi9Zf1awLxaC8qiDQnsCZ5tyVjNUFxTg',
    appId: '1:760455727775:web:6235a4d2c32a7bf36eb0aa',
    messagingSenderId: '760455727775',
    projectId: 'logins-app-6ef63',
    authDomain: 'logins-app-6ef63.firebaseapp.com',
    storageBucket: 'logins-app-6ef63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mUIefpVcdEB_yc5u7CPVxMNpDix85Pw',
    appId: '1:760455727775:android:7b300291663f81956eb0aa',
    messagingSenderId: '760455727775',
    projectId: 'logins-app-6ef63',
    storageBucket: 'logins-app-6ef63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgSUP7RUOPdNTuFfopz6edx9Sofbo0OA',
    appId: '1:760455727775:ios:d0013c1fb04444046eb0aa',
    messagingSenderId: '760455727775',
    projectId: 'logins-app-6ef63',
    storageBucket: 'logins-app-6ef63.appspot.com',
    iosClientId: '760455727775-ugr91qm534cosic4k6o5j3b93euti85a.apps.googleusercontent.com',
    iosBundleId: 'com.hiroyoshii.loginsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgSUP7RUOPdNTuFfopz6edx9Sofbo0OA',
    appId: '1:760455727775:ios:d0013c1fb04444046eb0aa',
    messagingSenderId: '760455727775',
    projectId: 'logins-app-6ef63',
    storageBucket: 'logins-app-6ef63.appspot.com',
    iosClientId: '760455727775-ugr91qm534cosic4k6o5j3b93euti85a.apps.googleusercontent.com',
    iosBundleId: 'com.hiroyoshii.loginsApp',
  );
}
