name: login-app
version: 0.1.0
summary: Login App
description: Login App that does everything!

confinement: strict
base: core18
grade: stable

slots:
  dbus-login-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.super_cool_app # adjust accordingly to your app name and
    
apps:
  login-app:
    command: super_cool_app
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-login-app
parts:
  login-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
