name: logins-app
version: 0.1.0
summary: Logins App
description: Logins App that does everything!

confinement: strict
base: core18
grade: stable

slots:
  dbus-logins-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.logins_app # adjust accordingly to your app name and
    
apps:
  logins-app:
    command: logins_app
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-logins-app
parts:
  logins-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    override-build: |
      set -ex
      # install yarn
      apt-get update
      apt-get install -y libwebkit2gtk-4.0-dev
      flutter build linux --release -v -t lib/main.dart
      cp -r ./build/linux/x64/release/bundle/ $SNAPCRAFT_PART_INSTALL/
